spring:
  application:
    name: petshop_api

  profiles:
    validate: true
#    active: "h2" # COMENTE ESSA LINHA PARA DESLIGAR O BANCO DE DADOS EM MEMÓRIA.

  datasource:
    username: petshop_user
    password: 12345678
    url: jdbc:mysql://localhost:3307/petshop_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    jdbc:
      dialect: mysql

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    web: debug